# **Introducción a PyTorch**

In [ ]:
import torch

In [ ]:
#Tensor de 1 dimensión

tensor_una_d= torch.LongTensor([0])
print(f'La forma de  {tensor_una_d} es {tensor_una_d.shape} y su dimensión es {tensor_una_d.dim()}' )

La forma de  tensor([0]) es torch.Size([1]) y su dimensión es 1


In [ ]:
#Otro tensor de 1 dimensión

tensor_una_d= torch.LongTensor([0, 1, 2])
print(f'La forma de  {tensor_una_d} es {tensor_una_d.shape} y su dimensión es {tensor_una_d.dim()}' )

La forma de  tensor([0, 1, 2]) es torch.Size([3]) y su dimensión es 1


In [ ]:
#Tensor de 2 dimensiones

tensor_dos_d= torch.LongTensor([[0, 1, 2], [3, 4, 5]])
print (tensor_dos_d)
print(f'La forma de  {tensor_dos_d} es {tensor_dos_d.shape} y su dimensión es {tensor_dos_d.dim()}' )

tensor([[0, 1, 2],
        [3, 4, 5]])
La forma de  tensor([[0, 1, 2],
        [3, 4, 5]]) es torch.Size([2, 3]) y su dimensión es 2


In [ ]:
#Otro tensor de 2 dimensiones

tensor_dos_d= torch.LongTensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print (tensor_dos_d)
print(f'La forma de  {tensor_dos_d} es {tensor_dos_d.shape} y su dimensión es {tensor_dos_d.dim()}' )

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
La forma de  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) es torch.Size([3, 3]) y su dimensión es 2


In [ ]:
# Tensor de 3 dimensiones
tensor_tres_d = torch.LongTensor([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
                                  [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
                                  [[18, 19, 20], [21, 22, 23], [24, 25, 26]]])
print(tensor_tres_d)
print(f'La forma de {tensor_tres_d} es {tensor_tres_d.shape} y su dimensión es {tensor_tres_d.dim()}')


tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
La forma de tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]) es torch.Size([3, 3, 3]) y su dimensión es 3
